# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: ac477e99a633912da1213741e2e75f62d5cc527c1006163470083016688fce3198b1dda1004ae2dcfd427bfb802ae81f786217d453f8e32d1e07e69ecb93b453
  fyber_api:
    key: <%= ENV["FYBER_API_KEY"] %>
    url: <%= ENV["FYBER_API_URL"] %>
  fyber_params:
    appid: <%= ENV["FYBER_APP_ID"] %>
    device_id: <%= ENV["FYBER_DEVICE_ID"] %>
    ip: <%= ENV["FYBER_IP"] %>
    offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
    locale: <%= ENV["FYBER_LOCALE"] %>

test:
  secret_key_base: 9ec5ce66407687bb6604b09a8006f59195b58a2e49668383e0066d9d5f220852d643549927a4e776c6f0912536df7a1b1a8a62056fc17025fd51f76da8b14f5b
  fyber_api:
    key: <%= ENV["FYBER_API_KEY"] %>
    url: <%= ENV["FYBER_API_URL"] %>
  fyber_params:
    appid: <%= ENV["FYBER_APP_ID"] %>
    device_id: <%= ENV["FYBER_DEVICE_ID"] %>
    ip: <%= ENV["FYBER_IP"] %>
    offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
    locale: <%= ENV["FYBER_LOCALE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fyber_api:
    key: <%= ENV["FYBER_API_KEY"] %>
    url: <%= ENV["FYBER_API_URL"] %>
  fyber_params:
    appid: <%= ENV["FYBER_APP_ID"] %>
    device_id: <%= ENV["FYBER_DEVICE_ID"] %>
    ip: <%= ENV["FYBER_IP"] %>
    offer_types: <%= ENV["FYBER_OFFER_TYPES"] %>
    locale: <%= ENV["FYBER_LOCALE"] %>
